name: Redeploy Discord Bot on Vultr

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install vultr-cli
      uses: techknowlogick/action-vultr@v2.3.0

    - name: Redeploy Discord Bot
      run: |
        # Get the IP address of the Vultr instance
        IP=$(vultr-cli instance list | grep "YourInstanceName" | awk '{print $3}')

        # SSH into the instance and run the update script
        ssh root@$IP 'cd /path/to/your/bot && git pull && pm2 restart your-bot-name'
