name: Redeploy Discord Bot on Vultr

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: GitHub Action for Vultr - vultr-cli
      uses: techknowlogick/action-vultr@v2.3.0
      with:
        # Vultr API Key
        token: ${{ 22RENWV4IVAPMTRMEQ5GQ4IHMIOJFHOEP66A }}
        
    - name: Redeploy Discord Bot
      run: |
        # Get the IP address of the Vultr instance
        IP=$(vultr-cli instance list | grep "my-project-server" | awk '{print $3}')

        # SSH into the instance and run the update script
        ssh root@$IP 'cd /root/discord-bot && pm2 stop Discord-Bot && git pull && npm run build && pm2 restart Discord-Bot'
